### ISSUE TITLE
Printing speed causes paths to generate slowly

### ISSUE THREAD

**Issue by andrewda** [TeamMeanMachine/PathVisualizer#1]
At least when running the jar file with debug output from the command-line, removing this `println` speeds up path generation and rendering by orders of magnitude.

https://github.com/TeamMeanMachine/PathVisualizer/blob/3d5c7d40a232aa990bf76c4a7ee00a41ccc8a495/src/main/kotlin/org/team2471/frc/pathvisualizer/PathVisualizer.kt#L1020

**Comment by bobcroucher** [comment]
We will remove it.  I'm sure it was added just for debugging purposes.
Thanks for discovering this...

**Comment by bobcroucher** [comment]
This offending code has been removed.
