### ISSUE TITLE
Allow panning over field

### ISSUE THREAD

**Issue by andrewda** [TeamMeanMachine/PathVisualizer#2]
Parts of the field are cut off on smaller screens (even on my 15" laptop) -- allowing people to pan over the field and move around would solve this issue.

An alternative/addition to this could be to zoom out about the center of the field instead of the bottom.

![image](https://user-images.githubusercontent.com/10191084/47334251-1d6e9100-d63b-11e8-8d48-5cf3d6b21f93.png)

**Comment by andrewda** [comment]
Apologies -- with a little further digging around, I realize that panning is already fully implemented, but right mouse button must be clicked. Thanks for thinking of this!

**Comment by bobcroucher** [comment]
It is also possible to zoom in or out with the mouse wheel or pinch zoom on
a touch screen.  There may be a third way, but I don't recall off hand.  So
you should be able to see the entire field even on a small screen.
