### ISSUE TITLE
Position and tangent fields are empty

### ISSUE THREAD

**Issue by andrewda** [TeamMeanMachine/PathVisualizer#9]
After selecting a point, the position and tangent text fields are empty.

![image](https://user-images.githubusercontent.com/10191084/51446907-19e7b600-1ccd-11e9-90a6-99f34b7428f2.png)

In addition, setting a new value for the point in the fields causes the point's position to update, but not the path. This can be fixed by dragging the point a little bit, which causes the path to update. I've been trying to debug this for a while, but haven't yet come across the cause.

![image](https://user-images.githubusercontent.com/10191084/51446992-16086380-1cce-11e9-9b01-5b91df903394.png)

**Comment by bobcroucher** [comment]
Fixed.  Sorry about the turmoil here.  I have a lot of students working on this, plus we did a big organizational refactoring.  We broke a few things.  Hopefully we will keep moving in the right direction.

**Comment by andrewda** [comment]
Great! Thanks for the quick fix!
